parameters:
#    msi_base.example.class: Msi\BaseBundle\Example

services:
#    msi_base.example:
#        class: %msi_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
